/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(fich_sink_b.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c48efa000a688041cb6de9f2f56f2c7b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ysf/fich_sink_b.h>
// pydoc.h is automatically generated in the build directory
#include <fich_sink_b_pydoc.h>

void bind_fich_sink_b(py::module& m)
{

    using fich_sink_b = gr::ysf::fich_sink_b;


    py::class_<fich_sink_b, gr::block, gr::basic_block, std::shared_ptr<fich_sink_b>>(
        m, "fich_sink_b", D(fich_sink_b))

        .def(py::init(&fich_sink_b::make), D(fich_sink_b, make))


        ;
}
