/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(fr_vch_decoder_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4de7298461b799b2ff9914f532b30f88)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ysf/fr_vch_decoder_bb.h>
// pydoc.h is automatically generated in the build directory
#include <fr_vch_decoder_bb_pydoc.h>

void bind_fr_vch_decoder_bb(py::module& m)
{

    using fr_vch_decoder_bb = gr::ysf::fr_vch_decoder_bb;


    py::class_<fr_vch_decoder_bb,
               gr::block,
               gr::basic_block,
               std::shared_ptr<fr_vch_decoder_bb>>(
        m, "fr_vch_decoder_bb", D(fr_vch_decoder_bb))

        .def(py::init(&fr_vch_decoder_bb::make), D(fr_vch_decoder_bb, make))


        ;
}
