/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pager_slicer_fb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d991685e3fc338ae283a659f1cd0157a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ysf/pager_slicer_fb.h>
// pydoc.h is automatically generated in the build directory
#include <pager_slicer_fb_pydoc.h>

void bind_pager_slicer_fb(py::module& m)
{

    using pager_slicer_fb = gr::ysf::pager_slicer_fb;


    py::class_<pager_slicer_fb,
               gr::block,
               gr::basic_block,
               std::shared_ptr<pager_slicer_fb>>(m, "pager_slicer_fb", D(pager_slicer_fb))

        .def(py::init(&pager_slicer_fb::make), py::arg("alpha"), D(pager_slicer_fb, make))


        ;
}
